basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name = 'detail'),
    path('create/', views.SchoolCreateView.as_view(), name = 'create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name = 'delete'),
]

classBV/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app')),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View,DetailView,TemplateView,ListView,CreateView,UpdateView,DeleteView
from . import models
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block body_block %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Delete {{school.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Yes">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
  </div>
  <div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    <p><a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
  </div>
{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
  </h1>

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>Welcome to the list of all the schools!</h1>
  <ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
  <a href="{% url 'basic_app:create' %}">Add New School</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block body_block %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page!</h1>
  </div>

{% endblock %}